-- drop database tcc;

CREATE DATABASE TCC;
USE TCC;

CREATE TABLE FUNCIONARIO(
	MATRICULA INT NOT NULL UNIQUE,
    NOME_FUNC NVARCHAR(255),
    CARGO NVARCHAR(50),
    CONSTRAINT MATRICULA_PK PRIMARY KEY (MATRICULA)
);

CREATE TABLE AUTOR (
    ID_AUTOR INT NOT NULL AUTO_INCREMENT,
    NOME_AUTOR NVARCHAR(50) NOT NULL,
    CONSTRAINT ID_AUTOR PRIMARY KEY (ID_AUTOR)
);

CREATE TABLE EDITORA (
    ID_EDITORA INT NOT NULL AUTO_INCREMENT,
    NOME_EDITORA NVARCHAR(50) NOT NULL,
    CONSTRAINT ID_EDITORA PRIMARY KEY (ID_EDITORA)
);

CREATE TABLE LIVRO (
    TOMBO INT NOT NULL AUTO_INCREMENT,
    TITULO NVARCHAR(50) NOT NULL,
    ENTRADA DATE NOT NULL,
    ETQ NVARCHAR(10) NOT NULL,
    ANO INT NOT NULL,
    V INT NOT NULL,
    EX INT NOT NULL,
    ID_EDITORA INT NOT NULL,
    ID_AUTOR INT NOT NULL,
    STATUS_LIVRO ENUM('EMPRESTADO', 'ESTANTE', 'EXTRAVIADO', 'RESERVADO', 'PERDIDO'),
    NOMENCLATURA ENUM ('LIN', 'LBR', 'POE', 'LES'),
    CONSTRAINT TOMBO_PK PRIMARY KEY (TOMBO),
    CONSTRAINT ID_EDITORA_FK FOREIGN KEY (ID_EDITORA)
        REFERENCES EDITORA (ID_EDITORA),
    CONSTRAINT ID_AUTOR_FK FOREIGN KEY (ID_AUTOR)
        REFERENCES AUTOR (ID_AUTOR)
);

CREATE TABLE SOCIO (
    ID_SOCIO INT NOT NULL AUTO_INCREMENT,
    NOME_SOCIO NVARCHAR(255) NOT NULL,
    RG CHAR(12) NOT NULL,
    NASC DATE NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    ASSOCIACAO DATETIME DEFAULT NOW(),
    NOME_PAI NVARCHAR(255),
    NOME_MAE NVARCHAR(255),
    CIDADE NVARCHAR(255),
    BAIRRO NVARCHAR(255),
    LOGRADOURO NVARCHAR(255),
    NUM NVARCHAR(20),
    TEL_RES NVARCHAR(20),
    CEL_1 NVARCHAR(20),
    CEL_2 NVARCHAR(20),
    CONSTRAINT ID_SOCIO PRIMARY KEY (ID_SOCIO)
);

CREATE TABLE EMPRESTIMO(
	RETIRADA DATE NOT NULL,
    DEVOLUCAO DATE NOT NULL,
    TOMBO INT NOT NULL,
    ID_SOCIO INT NOT NULL
);


SELECT 
    *
FROM
    SOCIO;
